# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './res/ui/TileMapPicker.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tile_map_picker(object):
    def setupUi(self, tile_map_picker):
        tile_map_picker.setObjectName("tile_map_picker")
        tile_map_picker.resize(424, 50)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(tile_map_picker.sizePolicy().hasHeightForWidth())
        tile_map_picker.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(tile_map_picker)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tile_map_name_combo = QtWidgets.QComboBox(tile_map_picker)
        self.tile_map_name_combo.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tile_map_name_combo.sizePolicy().hasHeightForWidth())
        self.tile_map_name_combo.setSizePolicy(sizePolicy)
        self.tile_map_name_combo.setObjectName("tile_map_name_combo")
        self.horizontalLayout.addWidget(self.tile_map_name_combo)
        self.add_tile_map_btn = QtWidgets.QToolButton(tile_map_picker)
        self.add_tile_map_btn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_tile_map_btn.sizePolicy().hasHeightForWidth())
        self.add_tile_map_btn.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_tile_map_btn.setIcon(icon)
        self.add_tile_map_btn.setObjectName("add_tile_map_btn")
        self.horizontalLayout.addWidget(self.add_tile_map_btn)
        self.remove_tile_map_btn = QtWidgets.QToolButton(tile_map_picker)
        self.remove_tile_map_btn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_tile_map_btn.sizePolicy().hasHeightForWidth())
        self.remove_tile_map_btn.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_tile_map_btn.setIcon(icon1)
        self.remove_tile_map_btn.setObjectName("remove_tile_map_btn")
        self.horizontalLayout.addWidget(self.remove_tile_map_btn)
        self.rename_tile_map_btn = QtWidgets.QToolButton(tile_map_picker)
        self.rename_tile_map_btn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rename_tile_map_btn.sizePolicy().hasHeightForWidth())
        self.rename_tile_map_btn.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/rename.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rename_tile_map_btn.setIcon(icon2)
        self.rename_tile_map_btn.setObjectName("rename_tile_map_btn")
        self.horizontalLayout.addWidget(self.rename_tile_map_btn)

        self.retranslateUi(tile_map_picker)
        QtCore.QMetaObject.connectSlotsByName(tile_map_picker)

    def retranslateUi(self, tile_map_picker):
        _translate = QtCore.QCoreApplication.translate
        tile_map_picker.setWindowTitle(_translate("tile_map_picker", "Form"))
        self.add_tile_map_btn.setText(_translate("tile_map_picker", "..."))
        self.remove_tile_map_btn.setText(_translate("tile_map_picker", "..."))
        self.rename_tile_map_btn.setText(_translate("tile_map_picker", "..."))
import resources_rc
