# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './res/ui/ColorPalette.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_color_palette(object):
    def setupUi(self, color_palette):
        color_palette.setObjectName("color_palette")
        color_palette.resize(615, 493)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(color_palette)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tool_layout = QtWidgets.QHBoxLayout()
        self.tool_layout.setObjectName("tool_layout")
        self.color_palette_name = QtWidgets.QComboBox(color_palette)
        self.color_palette_name.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.color_palette_name.sizePolicy().hasHeightForWidth())
        self.color_palette_name.setSizePolicy(sizePolicy)
        self.color_palette_name.setObjectName("color_palette_name")
        self.tool_layout.addWidget(self.color_palette_name)
        self.add_color_palette = QtWidgets.QToolButton(color_palette)
        self.add_color_palette.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_color_palette.sizePolicy().hasHeightForWidth())
        self.add_color_palette.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_color_palette.setIcon(icon)
        self.add_color_palette.setObjectName("add_color_palette")
        self.tool_layout.addWidget(self.add_color_palette)
        self.remove_color_palette = QtWidgets.QToolButton(color_palette)
        self.remove_color_palette.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_color_palette.sizePolicy().hasHeightForWidth())
        self.remove_color_palette.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_color_palette.setIcon(icon1)
        self.remove_color_palette.setObjectName("remove_color_palette")
        self.tool_layout.addWidget(self.remove_color_palette)
        self.rename_color_palette = QtWidgets.QToolButton(color_palette)
        self.rename_color_palette.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rename_color_palette.sizePolicy().hasHeightForWidth())
        self.rename_color_palette.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/rename.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rename_color_palette.setIcon(icon2)
        self.rename_color_palette.setObjectName("rename_color_palette")
        self.tool_layout.addWidget(self.rename_color_palette)
        self.verticalLayout_2.addLayout(self.tool_layout)
        self.palette_layout = QtWidgets.QHBoxLayout()
        self.palette_layout.setObjectName("palette_layout")
        self.color_layout = QtWidgets.QGridLayout()
        self.color_layout.setSpacing(0)
        self.color_layout.setObjectName("color_layout")
        self.palette_layout.addLayout(self.color_layout)
        self.color_preview = ColorPreview(color_palette)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.color_preview.sizePolicy().hasHeightForWidth())
        self.color_preview.setSizePolicy(sizePolicy)
        self.color_preview.setMinimumSize(QtCore.QSize(95, 95))
        self.color_preview.setObjectName("color_preview")
        self.palette_layout.addWidget(self.color_preview)
        self.verticalLayout_2.addLayout(self.palette_layout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)

        self.retranslateUi(color_palette)
        QtCore.QMetaObject.connectSlotsByName(color_palette)

    def retranslateUi(self, color_palette):
        _translate = QtCore.QCoreApplication.translate
        color_palette.setWindowTitle(_translate("color_palette", "Form"))
        self.add_color_palette.setText(_translate("color_palette", "..."))
        self.remove_color_palette.setText(_translate("color_palette", "..."))
        self.rename_color_palette.setText(_translate("color_palette", "..."))
from color_preview import ColorPreview
import resources_rc
