# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './res/ui/PixelPalette.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pixel_palette(object):
    def setupUi(self, pixel_palette):
        pixel_palette.setObjectName("pixel_palette")
        pixel_palette.resize(625, 571)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(pixel_palette)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tool_layout = QtWidgets.QHBoxLayout()
        self.tool_layout.setObjectName("tool_layout")
        self.add_pixel_palette = QtWidgets.QToolButton(pixel_palette)
        self.add_pixel_palette.setEnabled(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_pixel_palette.setIcon(icon)
        self.add_pixel_palette.setObjectName("add_pixel_palette")
        self.tool_layout.addWidget(self.add_pixel_palette)
        self.remove_pixel_palette = QtWidgets.QToolButton(pixel_palette)
        self.remove_pixel_palette.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_pixel_palette.setIcon(icon1)
        self.remove_pixel_palette.setObjectName("remove_pixel_palette")
        self.tool_layout.addWidget(self.remove_pixel_palette)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.tool_layout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.tool_layout)
        self.palette_layout = QtWidgets.QHBoxLayout()
        self.palette_layout.setObjectName("palette_layout")
        self.palette_view = QtWidgets.QGraphicsView(pixel_palette)
        self.palette_view.setEnabled(False)
        self.palette_view.setObjectName("palette_view")
        self.palette_layout.addWidget(self.palette_view)
        self.verticalLayout_2.addLayout(self.palette_layout)

        self.retranslateUi(pixel_palette)
        QtCore.QMetaObject.connectSlotsByName(pixel_palette)

    def retranslateUi(self, pixel_palette):
        _translate = QtCore.QCoreApplication.translate
        pixel_palette.setWindowTitle(_translate("pixel_palette", "Form"))
        self.add_pixel_palette.setText(_translate("pixel_palette", "..."))
        self.remove_pixel_palette.setText(_translate("pixel_palette", "..."))
import resources_rc
